// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class CodigoComputo
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public virtual ICollection<Component> Components { get; set; } = new List<Component>();
}