// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class Component
{
    public int Id { get; set; }

    public bool? EstadoActivo { get; set; }

    public int? IdArticulos { get; set; }

    public int? IdCodigoComputos { get; set; }

    public int? IdHistorialComponente { get; set; }

    public int? IdMetodoAdquisicion { get; set; }

    public string NumPatrimonio { get; set; }

    public virtual Articulo IdArticulosNavigation { get; set; }

    public virtual CodigoComputo IdCodigoComputosNavigation { get; set; }

    public virtual ComponentesHistoriale IdHistorialComponenteNavigation { get; set; }

    public virtual MetodosAdquisicion IdMetodoAdquisicionNavigation { get; set; }

    public virtual ICollection<Pc> Pcs { get; set; } = new List<Pc>();
}