// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class MetodosAdquisicion
{
    public int Id { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdCajaChica { get; set; }

    public int? IdPedido { get; set; }

    public string Otro { get; set; }

    public virtual ICollection<Component> Components { get; set; } = new List<Component>();

    public virtual CajaChica IdCajaChicaNavigation { get; set; }

    public virtual Pedido IdPedidoNavigation { get; set; }
}