// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class Pc
{
    public int Id { get; set; }

    public int? IdComponent { get; set; }

    public int? IdPcHistorial { get; set; }

    public int? IdPcNombres { get; set; }

    public int? IdServices { get; set; }

    public virtual Component IdComponentNavigation { get; set; }

    public virtual PcHistoriale IdPcHistorialNavigation { get; set; }

    public virtual PcNombre IdPcNombresNavigation { get; set; }

    public virtual Servicio IdServicesNavigation { get; set; }
}