// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class PcNombre
{
    public int Id { get; set; }

    public string Ip { get; set; }

    public string UserPc { get; set; }

    public virtual ICollection<Pc> Pcs { get; set; } = new List<Pc>();
}