// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class Proveedore
{
    public int Id { get; set; }

    public string Contacto { get; set; }

    public string Historial { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<CajaChica> CajaChicas { get; set; } = new List<CajaChica>();

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}