// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class User
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Rol { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Carga> Cargas { get; set; } = new List<Carga>();

    public virtual ICollection<PcHistoriale> PcHistoriales { get; set; } = new List<PcHistoriale>();
}