// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class CajaChica
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public int? IdProveedor { get; set; }

    public decimal? Monto { get; set; }

    public string NumCaja { get; set; }

    public bool? Pago { get; set; }

    public virtual Proveedore IdProveedorNavigation { get; set; }

    public virtual ICollection<MetodosAdquisicion> MetodosAdquisicions { get; set; } = new List<MetodosAdquisicion>();
}