// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class Carga
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public int? IdService { get; set; }

    public int? IdToner { get; set; }

    public int? IdUsuario { get; set; }

    public virtual Servicio IdServiceNavigation { get; set; }

    public virtual Toner IdTonerNavigation { get; set; }

    public virtual User IdUsuarioNavigation { get; set; }
}