// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class PcHistoriale
{
    public int Id { get; set; }

    public string Detalle { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdUser { get; set; }

    public virtual User IdUserNavigation { get; set; }

    public virtual ICollection<Pc> Pcs { get; set; } = new List<Pc>();
}