// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PatrimonioAPI.Models;

public partial class Servicio
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Carga> Cargas { get; set; } = new List<Carga>();

    public virtual ICollection<Pc> Pcs { get; set; } = new List<Pc>();
}